runtime: ruby
env: flex
entrypoint: bundle exec rails server -p $PORT

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:

beta_settings:
  cloud_sql_instances: jellyposter:us-west1:jellyposter-prod-pg