version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '2.5.7'
        PG_MAJOR: '11'
        NODE_MAJOR: '12'
        YARN_VERSION: '1.13.0'
        BUNDLER_VERSION: '2.1.0'
    image: jelly:1.1.0
    tmpfs:
      - /tmp
    volumes:
      - .:/app
      # - rails_cache:/app/tmp/cache
      # - bundle:/usr/local/bundle
      # - node_modules:/app/node_modules
      # - packs:/app/public/packs
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vi
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'


  # grobid:
  #   image: lfoppiano/grobid:0.5.6
  #   restart: on-failure
  #   ports:
  #     - "8070:8070"
  #     - "8071:8071"
  #   expose:
  #     - "8070"
  # postgres:
  #   image: postgres:12
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=jelly
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - "5432"
  # redis:
  #   image: redis:5.0.7
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   expose:
  #     - "6379"
  # figures:
  #   image: dluan/figures:0.0.5
  #   ports:
  #     - "4567:4567"
  #   expose:
  #     - "4567"
