default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 30000

development:
  <<: *default
  database: jellyposter_development
  port: 5432

test:
  <<: *default
  database: jellyposter_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['PUMA_MAX_THREADS'] || 5 %>
  database: "jellyposter-prod"
